Models/food.cs
namespace Project_KFC_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("food")]
    public partial class food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public food()
        {
            carts = new HashSet<cart>();
        }

        [DisplayName("Mã món ăn")]
        public int id { get; set; }

        [DisplayName("Loại món ăn")]
        public int? idCategory { get; set; }

        [DisplayName("Tên món ăn")]
        public string name { get; set; }

        [DisplayName("Ảnh")]
        public string image { get; set; }

        [DisplayName("Giá")]
        public double? price { get; set; }

        [DisplayName("Giảm giá(%)")]
        public double? discount { get; set; }

        [DisplayName("Mô tả")]
        public string description { get; set; }

        [DisplayName("Ngày giảm giá")]
        [Column(TypeName = "date")]
        public DateTime? timeSellStart { get; set; }

        [DisplayName("Ngày kết thúc")]
        [Column(TypeName = "date")]
        public DateTime? timeSellEnd { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }

        public virtual foodCategory foodCategory { get; set; }
    }
}

Areas/Admin/Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_KFC_WEB.Models;

namespace Project_KFC_WEB.Areas.Admin.Controllers
{
    public class FoodsController : Controller
    {
        private KFC_Data db = new KFC_Data();

        // GET: Admin/Foods
        public ActionResult Index(int page = 1, bool isReset = false)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            if (isReset) Session["isSearchingFood"] = false;

            List<food> foods = new List<food>();
            bool isSearching = Session["isSearchingFood"] != null ? (bool)Session["isSearchingFood"] : false;

            var selectedCategoryOption = Request.QueryString["selectedCategoryOption"];
            var selectedOptionPrice = Request.QueryString["selectedOptionPrice"];
            var checkSale = Request.QueryString["checkSale"];
            var valueSearch = Request.QueryString["valueSearch"];

            foods = db.foods.Include(c => c.foodCategory).ToList();
            ViewBag.foodCategories = db.foodCategories.ToList();

            if (!isSearching)
            {
                    if (!string.IsNullOrEmpty(selectedOptionPrice) || !string.IsNullOrEmpty(valueSearch) || !string.IsNullOrEmpty(checkSale) || !string.IsNullOrEmpty(selectedCategoryOption))
                    {
                        isSearching = true;
                        Session["isSearchingFood"] = isSearching;
                        foods = SrearchFood(foods, selectedCategoryOption, selectedOptionPrice, valueSearch, checkSale);
                    }
            }

            if (isSearching)
            {
                foods = Session["listFood"] as List<food>;
                if (foods.ToList().Count() == 0) Session["isSearchingFood"] = false;
                foods = SrearchFood(foods, selectedCategoryOption, selectedOptionPrice, valueSearch, checkSale);
            }

            int itemsPerPage = 5;
            int totalItems = foods.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / itemsPerPage);

            page = Math.Max(1, Math.Min(page, totalPages));

            var startIndex = (page - 1) * itemsPerPage;
            var endIndex = Math.Min(startIndex + itemsPerPage - 1, totalItems - 1);

            List<food> foodPage;

            if (startIndex < 0 || startIndex >= totalItems)
            {
                foodPage = null;
            }
            else
            {
                foodPage = foods.GetRange(startIndex, endIndex - startIndex + 1);
            }

            ViewBag.currentPage = page;
            Session["currentPageFood"] = page;
            ViewBag.totalPages = totalPages;

            return View(foodPage);
        }

        public List<food> SrearchFood(List<food> foods, string selectedCategoryOption, string selectedOptionPrice, string valueSearch, string checkSale)
        {
            if (!string.IsNullOrEmpty(selectedCategoryOption)) foods = foods.FindAll(item => item.foodCategory.name.ToLower().Equals(selectedCategoryOption.Trim().ToLower()));

            if (!string.IsNullOrEmpty(selectedOptionPrice))
            {
                var number = Convert.ToInt32(string.Join("", selectedOptionPrice.Split('-')[0].Trim().Split('.')));

                if (number == 0)
                {
                    foods = foods.FindAll(item => item.price >= 0 && item.price < 10000);
                }
                else if (number == 10000)
                {
                    foods = foods.FindAll(item => item.price >= 10000 && item.price < 50000);
                }
                else if (number == 50000)
                {
                    foods = foods.FindAll(item => item.price >= 50000 && item.price < 100000);
                }
                else if (number == 100000)
                {
                    foods = foods.FindAll(item => item.price >= 100000 && item.price < 500000);

                }
                else if (number == 500000)
                {
                    foods = foods.FindAll(item => item.price >= 500000 && item.price < 1000000);

                }
                else if (number == 1000000)
                {
                    foods = foods.FindAll(item => item.price >= 1000000);

                }
            }

            if (!string.IsNullOrEmpty(valueSearch)) foods = foods.FindAll(item => item.name.ToLower().Contains(valueSearch.Trim().ToLower()));

            if (checkSale != null) foods = checkSale.Contains("on") ? foods.FindAll(item => item.discount > 0) : foods;

            Session["listFood"] = foods;

            return foods;
        }

        // GET: Admin/Foods/Details/5
        public ActionResult Details(int? id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            food food = db.foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            return View(food);
        }

        // GET: Admin/Foods/Create
        public ActionResult Create()
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });


            ViewBag.idCategory = new SelectList(db.foodCategories, "id", "name");
            return View();
        }

        // POST: Admin/Foods/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,idCategory,name,image,price,discount,description,timeSellStart,timeSellEnd")] food food, HttpPostedFileBase imageFile)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(imageFile.FileName);
                    string path = Path.Combine(Server.MapPath("~/Upload"), fileName);
                    imageFile.SaveAs(path);
                    food.image = fileName;
                }

                var lastFood = db.foods.OrderByDescending(f => f.id).FirstOrDefault();

                if (lastFood != null)
                {
                    food.id = lastFood.id + 1;
                }
                else
                {
                    food.id = 1;
                }

                db.foods.Add(food);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(food);
        }

        // GET: Admin/Foods/Edit/5
        public ActionResult Edit(int? id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            food food = db.foods.Find(id);
            if (food == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCategory = new SelectList(db.foodCategories, "id", "name", food.idCategory);
            return View(food);
        }

        // POST: Admin/Foods/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,idCategory,name,image,price,discount,description,timeSellStart,timeSellEnd")] food food, HttpPostedFileBase imageFile)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(imageFile.FileName);
                    string path = Path.Combine(Server.MapPath("~/Upload"), fileName);
                    imageFile.SaveAs(path);
                    food.image = fileName;

                    db.Entry(food).State = EntityState.Modified;
                }
                else
                {
                    var existingFood = db.foods.FirstOrDefault(item => item.id == food.id);

                    if (existingFood != null)
                    {
                        existingFood.idCategory = food.idCategory;
                        existingFood.name = food.name;
                        existingFood.price = food.price;
                        existingFood.discount = food.discount;
                        existingFood.description = food.description;
                        existingFood.timeSellStart = food.timeSellStart;
                        existingFood.timeSellEnd = food.timeSellEnd;

                        db.Entry(existingFood).State = EntityState.Modified;
                    }
                    else
                    {

Areas/Admin/Views/Foods/Create.cshtml
@model Project_KFC_WEB.Models.food

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Create", "Foods", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

<div class="form-horizontal box-header with-border">
    <div class="box-header with-border">
        <h2 class="box-title" style="font-size: x-large; padding-left: 10px; font-weight: 700; color: green; ">Tạo mới loại món ăn</h2>
        <div class="box-tools pull-right">
            <button class="btn btn-info btn-sm" type="submit"><i class="fa fa-check"></i> Tạo mới</button>
            <button class="btn btn-default btn-sm" type="reset"><i class="fa fa-refresh"></i> Làm mới dữ liệu</button>
        </div>
    </div>
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.idCategory, "idCategory", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("idCategory", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idCategory, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="imageFile" name="imageFile" class="form-control" onchange="previewImage(this);" />
            <img id="imagePreview" src="#" alt="Vui lòng chọn ảnh" style="max-width: 100%; max-height: 150px; margin-top: 10px;" />
            <button type="button" id="btnRemoveImage" class="btn btn-danger btn-sm" style="margin-top: 10px; display: none;" onclick="removeImage();"><i class="fa fa-trash"></i> Xóa ảnh</button>
            @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control", @type = "number", @step = "any" } })
            @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.discount, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.discount, new { htmlAttributes = new { @class = "form-control",  @type = "number", @step = "any" } })
            @Html.ValidationMessageFor(model => model.discount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

</div>
}

<div>
    <a class="btn btn-default btn-sm" style="margin-left: 10px; margin-top: 10px" href="@Url.Action("Index", "Foods")"><i class="fa fa-solid fa-arrow-left"></i> Quay lại</a>
</div>
<script>
    function previewImage(input) {
        var file = input.files[0];
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#imagePreview').attr('src', e.target.result);
            $('#imagePreview').show();
            $('#btnRemoveImage').show();
        }

        reader.readAsDataURL(file);
    }

    function removeImage() {
        $('#imagePreview').attr('src', '#');
        $('#imagePreview').hide();
        $('#btnRemoveImage').hide();
        $('#imageFile').val('');
    }
</script>

Areas/Admin/Views/Foods/Delete.cshtml
@model Project_KFC_WEB.Models.food

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div>
    <br />
    <h2 class="box-title" style="font-size: 24px; padding-left: 10px; font-weight: 700; color: green; ">Bạn có chắc chắn muốn xóa món ăn này ?</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.foodCategory.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foodCategory.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img src="~/Upload/@Model.image" style="width: 200px; height:100%" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="box-tools pull-left">
            <a class="btn btn-default btn-sm" style="margin-left: 10px" href="@Url.Action("Index", "Foods", new { page = (int)Session["currentPageFood"] })"><i class="fa fa-solid fa-arrow-left"></i> Quay lại</a>
            <button class="btn btn-sm alert-danger" type="submit" style="margin-left:10px"><i class="fa fa-check"></i> xóa thức ăn</button>
        </div>
    }
</div>

Areas/Admin/Views/Foods/Details.cshtml
@model Project_KFC_WEB.Models.food

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>food</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.foodCategory.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foodCategory.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.timeSellStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.timeSellStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.timeSellEnd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.timeSellEnd)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Admin/Views/Foods/Edit.cshtml
@model Project_KFC_WEB.Models.food

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Edit", "Foods", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal box-header with-border">
        <div class="box-header with-border">
            <h2 class="box-title" style="font-size: x-large; padding-left: 10px; font-weight: 700; color: green; ">Chỉnh sửa món ăn</h2>
            <div class="box-tools pull-right">
                <button class="btn btn-info btn-sm" type="submit"><i class="fa fa-check"></i> Lưu lại</button>
            </div>
        </div>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.idCategory, "idCategory", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCategory", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="imageFile" name="imageFile" class="form-control" onchange="previewImage(this);" />
                <img id="imagePreview" src="~/Upload/@Model.image" alt="Vui lòng chọn ảnh" style="max-width: 100%; max-height: 150px; margin-top: 10px;" />
                <button type="button" id="btnRemoveImage" class="btn btn-danger btn-sm" style="margin-top: 10px;" onclick="removeImage();"><i class="fa fa-trash"></i>Xóa ảnh</button>
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control", @type = "number", @step = "any" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.discount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.discount, new { htmlAttributes = new { @class = "form-control", @type = "number", @step = "any" } })
                @Html.ValidationMessageFor(model => model.discount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}
<div>
    <a class="btn btn-default btn-sm" style="margin-left: 10px; margin-top: 10px" href="@Url.Action("Index", "Foods", new { page = (int)Session["currentPageFood"] })"><i class="fa fa-solid fa-arrow-left"></i> Quay lại</a>
</div>
<script>
    function previewImage(input) {
        var file = input.files[0];
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#imagePreview').attr('src', e.target.result);
            $('#imagePreview').show();
            $('#btnRemoveImage').show();
        }

        reader.readAsDataURL(file);
    }

    function removeImage() {
        $('#imagePreview').attr('src', '#');
        $('#imagePreview').hide();
        $('#btnRemoveImage').hide();
        $('#imageFile').val('');
    }
</script>