Models/foodCategory.cs
namespace Project_KFC_WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("foodCategory")]
    public partial class foodCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public foodCategory()
        {
            foods = new HashSet<food>();
        }

        [DisplayName("Mã loại")]
        public int id { get; set; }

        [DisplayName("Tên loại món ăn")]
        public string name { get; set; }

        [DisplayName("Ảnh")]
        public string image { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<food> foods { get; set; }
    }
}

Areas/Admin/Controllers/FoodCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_KFC_WEB.Models;

namespace Project_KFC_WEB.Areas.Admin.Controllers
{
    public class FoodCategoriesController : Controller
    {
        private KFC_Data db = new KFC_Data();

        // GET: Admin/FoodCategories
        public ActionResult Index(int page = 1, bool isReset = false)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            if (isReset) Session["isSearchingFoodCategory"] = false;

            List<foodCategory> foodCategories = new List<foodCategory>();
            bool isSearching = Session["isSearchingFoodCategory"] != null ? (bool)Session["isSearchingFoodCategory"] : false;

            var valueSearch = Request.QueryString["valueSearch"];

            foodCategories = db.foodCategories.ToList();

            if (!isSearching)
            {
                if (!string.IsNullOrEmpty(valueSearch))
                {
                    isSearching = true;
                    foodCategories = foodCategories.FindAll(item => item.name.ToLower().Contains(valueSearch.Trim().ToLower()));
                    Session["listFoodCategoty"] = foodCategories;
                }
            }

            if (isSearching)
            {
                foodCategories = Session["listFoodCategoty"] as List<foodCategory>;
                if (foodCategories.ToList().Count() == 0) Session["isSearchingFoodCategory"] = false;
                if (!string.IsNullOrEmpty(valueSearch))
                {
                    foodCategories = foodCategories.FindAll(item => item.name.ToLower().Contains(valueSearch.Trim().ToLower()));
                    Session["listFoodCategoty"] = foodCategories;
                }
            }

            int itemsPerPage = 5;
            int totalItems = foodCategories.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / itemsPerPage);

            page = Math.Max(1, Math.Min(page, totalPages));

            var startIndex = (page - 1) * itemsPerPage;
            var endIndex = Math.Min(startIndex + itemsPerPage - 1, totalItems - 1);

            List<foodCategory> foodCategoryPage;

            if (startIndex < 0 || startIndex >= totalItems)
            {
                foodCategoryPage = null;
            }
            else
            {
                foodCategoryPage = foodCategories.GetRange(startIndex, endIndex - startIndex + 1);
            }

            ViewBag.currentPage = page;
            Session["currentPageFoodCategory"] = page;
            ViewBag.totalPages = totalPages;


            return View(foodCategoryPage);
        }

        // GET: Admin/FoodCategories/Details/5
        public ActionResult Details(int? id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            foodCategory foodCategory = db.foodCategories.FirstOrDefault((item) => item.id == id);
            if (foodCategory == null)
            {
                return HttpNotFound();
            }
            return View(foodCategory);
        }

        // GET: Admin/FoodCategories/Create
        public ActionResult Create()
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            return View();
        }

        // POST: Admin/FoodCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,image")] foodCategory foodCategory, HttpPostedFileBase imageFile)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(imageFile.FileName);
                    string path = Path.Combine(Server.MapPath("~/Upload"), fileName);
                    imageFile.SaveAs(path);
                    foodCategory.image = fileName;
                }

                var lastFoodCategory = db.foodCategories.OrderByDescending(fc => fc.id).FirstOrDefault();

                if (lastFoodCategory != null)
                {
                    foodCategory.id = lastFoodCategory.id + 1;
                }
                else
                {
                    foodCategory.id = 1;
                }

                db.foodCategories.Add(foodCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(foodCategory);
        }

        // GET: Admin/FoodCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            foodCategory foodCategory = db.foodCategories.FirstOrDefault((item) => item.id == id);
            if (foodCategory == null)
            {
                return HttpNotFound();
            }
            return View(foodCategory);
        }

        // POST: Admin/FoodCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,image")] foodCategory foodCategory, HttpPostedFileBase imageFile)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(imageFile.FileName);
                    string path = Path.Combine(Server.MapPath("~/Upload"), fileName);
                    imageFile.SaveAs(path);
                    foodCategory.image = fileName;
                    db.Entry(foodCategory).State = EntityState.Modified;
                }
                else
                {
                    var existingFoodCategory = db.foodCategories.FirstOrDefault(item => item.id == foodCategory.id);

                    if (existingFoodCategory != null)
                    {
                        existingFoodCategory.name = foodCategory.name;
                        db.Entry(existingFoodCategory).State = EntityState.Modified;
                    }
                    else
                    {
                        return HttpNotFound();
                    }

                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(foodCategory);
        }


        // GET: Admin/FoodCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            foodCategory foodCategory = db.foodCategories.FirstOrDefault((item) => item.id == id);
            if (foodCategory == null)
            {
                return HttpNotFound();
            }
            return View(foodCategory);
        }

        // POST: Admin/FoodCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if (!isLogin) return RedirectToAction("Login", "Home", new { isLogin = false });

            foodCategory foodCategory = db.foodCategories.FirstOrDefault((item) => item.id == id);
            db.foodCategories.Remove(foodCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/FoodCategories/Create.cshtml
@model Project_KFC_WEB.Models.foodCategory

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "FoodCategories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal box-header with-border">
        <div class="box-header with-border">
            <h2 class="box-title" style="font-size: x-large; padding-left: 10px; font-weight: 700; color: green; ">Tạo mới loại món ăn</h2>
            <div class="box-tools pull-right">
                <button class="btn btn-info btn-sm" type="submit"><i class="fa fa-check"></i> Tạo mới</button>
                <button class="btn btn-default btn-sm" type="reset"><i class="fa fa-refresh"></i> Làm mới dữ liệu</button>
            </div>
        </div>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="imageFile" name="imageFile" class="form-control" onchange="previewImage(this);" />
                <img id="imagePreview" src="#" alt="Vui lòng chọn ảnh" style="max-width: 100%; max-height: 150px; margin-top: 10px;" />
                <button type="button" id="btnRemoveImage" class="btn btn-danger btn-sm" style="margin-top: 10px; display: none;" onclick="removeImage();"><i class="fa fa-trash"></i> Xóa ảnh</button>
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-default btn-sm" style="margin-left: 10px; margin-top: 10px" href="@Url.Action("Index", "FoodCategories")"><i class="fa fa-solid fa-arrow-left"></i> Quay lại</a>
</div>

<script>
    function previewImage(input) {
        var file = input.files[0];
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#imagePreview').attr('src', e.target.result);
            $('#imagePreview').show();
            $('#btnRemoveImage').show();
        }

        reader.readAsDataURL(file);
    }

    function removeImage() {
        $('#imagePreview').attr('src', '#');
        $('#imagePreview').hide();
        $('#btnRemoveImage').hide();
        $('#imageFile').val('');
    }
</script>

Areas/Admin/Views/FoodCategories/Delete.cshtml
@model Project_KFC_WEB.Models.foodCategory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div>
    <br />
    <h2 class="box-title" style="font-size: 24px; padding-left: 10px; font-weight: 700; color: green; ">Bạn có chắc chắn muốn xóa loại thức ăn này ?</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img src="~/Upload/@Model.image" style="width: 200px; height:100%" />
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="box-tools pull-left">
            <a class="btn btn-default btn-sm" style="margin-left: 10px" href="@Url.Action("Index", "FoodCategories",new { page = (int)Session["currentPageFoodCategory"] })"><i class="fa fa-solid fa-arrow-left"></i> Quay lại</a>
            <button class="btn btn-sm alert-danger" type="submit" style="margin-left:10px"><i class="fa fa-check"></i> Xóa loại thức ăn</button>
        </div>
    }
</div>

Areas/Admin/Views/FoodCategories/Details.cshtml
@model Project_KFC_WEB.Models.foodCategory

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>foodCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Areas/Admin/Views/FoodCategories/Edit.cshtml
@model Project_KFC_WEB.Models.foodCategory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "FoodCategories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal box-header with-border">
        <div class="box-header with-border">
            <h2 class="box-title" style="font-size: x-large; padding-left: 10px; font-weight: 700; color: green; ">Chỉnh sửa loại món ăn</h2>
            <div class="box-tools pull-right">
                <button class="btn btn-info btn-sm" type="submit"><i class="fa fa-check"></i> Lưu lại</button>
            </div>
        </div>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="imageFile" name="imageFile" class="form-control" onchange="previewImage(this);" />
                <img id="imagePreview" src="~/Upload/@Model.image" alt="Vui lòng chọn ảnh" style="max-width: 100%; max-height: 150px; margin-top: 10px;" />
                <button type="button" id="btnRemoveImage" class="btn btn-danger btn-sm" style="margin-top: 10px;" onclick="removeImage();"><i class="fa fa-trash"></i>Xóa ảnh</button>
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-default btn-sm" style="margin-left: 10px; margin-top: 10px" href="@Url.Action("Index", "FoodCategories", new { page = (int)Session["currentPageFoodCategory"] })"><i class="fa fa-solid fa-arrow-left"></i> Quay lại</a>

</div>
<script>
    function previewImage(input) {
        var file = input.files[0];
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#imagePreview').attr('src', e.target.result);
            $('#imagePreview').show();
            $('#btnRemoveImage').show();
        }

        reader.readAsDataURL(file);
    }

    function removeImage() {
        $('#imagePreview').attr('src', '#');
        $('#imagePreview').hide();
        $('#btnRemoveImage').hide();
        $('#imageFile').val('');
    }
</script>

Areas/Admin/Views/FoodCategories/Index.cshtml
@model IEnumerable<Project_KFC_WEB.Models.foodCategory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="~/Areas/Admin//Data/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Areas/Admin//Data/plugins/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Areas/Admin//Data/plugins/ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Areas/Admin//Data/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/Areas/Admin//Data/dist/css/skins/_all-skins.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!--css custom page-->
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Areas/Admin//Data/plugins/datatables/dataTables.bootstrap.css">

    <!--end css custom page-->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <!-- Left side column. contains the logo and sidebar -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    @*<section class="content-header">
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        Danger alert preview. This alert is dismissable. A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.
                    </div>
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4>	<i class="icon fa fa-check"></i> Alert!</h4>
                        Success alert preview. This alert is dismissable.
                    </div>
                </div>
            </div>
        </section>*@
    <!-- Main content -->
    <section class="content">
        <div style="width: 100%; display: flex; justify-content: center">

            <span style="font-size: x-large; padding-left: 10px; font-weight: 700; color: #333; font-size: 26px">Quản lí loại món ăn</span>
        </div>
        @using (Html.BeginForm("Index", "FoodCategories", FormMethod.Get, new { @class = "sidebar-form", style = "border: none;" }))
        {
            <a href="@Url.Action("Index", "FoodCategories", new {  page = 1, isReset = true})" class="btn btn-info btn-reset" style="color: #fff !important; background-color: #5bc0de !important; border-color: #46b8da !important; ">Tải lại loại món ăn</a>

            <div class="input-group" style="margin-top: 20px;">
                <input type="text" name="valueSearch" class="form-control" placeholder="Nhập loại món ăn muốn tìm...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        }
        <div class="row">
            <div class="col-xs-12">
                <div class="box ">
                    <div class="box-header">
                        <a href="@Url.Action("Create")" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Tạo loại món ăn</a>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <table id="example" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.id)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.image)
                                    </th>
                                    <th>Chức năng </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    @if (Model != null)
                                    {

                                        foreach (var item in Model)
                                        {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.id)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.name)
                                            </td>
                                            <td>
                                                <img src="~/Upload/@item.image" style="width: 200px; height:100%" />
                                            </td>

                                            <td>
                                                <a class="btn btn-info btn-xs" href="@Url.Action("Edit", "FoodCategories", new {  id=item.id})"><i class="fa fa-pencil"></i>Chỉnh sửa</a>
                                                <a class="btn btn-danger btn-xs" href="@Url.Action("Delete", "FoodCategories", new {  id=item.id})"><i class="fa fa-trash"></i>Xóa</a>
                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <div class="text-danger ">Không có dữ liệu</div>

                                }

                                </tbody>
                            </table>
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div><!-- /.col -->
            </div><!-- /.row -->
            @* page  *@
            <div style="background-color: white; display: flex; justify-content: space-between; height: 40px; align-items: center; padding: 20px; border-radius: 4px;">
                <div style="display:flex; column-gap: 10px">
                    <a href="@Url.Action("Index", "Foodcategories", new {  page = 1})" class="btn btn-info">Trang đầu</a>
                    <a href="@Url.Action("Index", "Foodcategories", new {  page = Convert.ToInt32(ViewBag.currentPage) + 1})" class="btn btn-info">Trang tiếp</a>
                    <a href="@Url.Action("Index", "Foodcategories", new {  page = Convert.ToInt32(ViewBag.totalPages)})" class="btn btn-info">Trang cuối</a>
                </div>
                <ul style="display: flex; column-gap: 10px; align-items: center">
                    <span style="margin-top: 5px; color: red; font-size: large; font-weight: 600 ">Trang: </span>
                    @{
                        for (int i = 1; i <= Convert.ToInt32(ViewBag.totalPages); i++)
                        {
                            if (i == Convert.ToInt32(ViewBag.currentPage))
                            {
                                <li style="list-style: none; cursor: pointer; margin-top: 5px;"><a style="color: red; font-size: large">@i</a></li>
                            }
                            else
                            {
                                <li style="list-style: none; cursor: pointer; margin-top: 5px;"><a href="@Url.Action("Index", "Foodcategories", new {  page = i})" style="color: #333; font-size: large">@i</a></li>
                            }
                        }
                    }
                </ul>
            </div>
            </div><!-- ./wrapper -->
            <!-- jQuery 2.1.4 -->
            <script src="~/Areas/Admin//Data/plugins/jQuery/jQuery-2.1.4.min.js"></script>
            <!-- Bootstrap 3.3.5 -->
            <script src="~/Areas/Admin//Data/bootstrap/js/bootstrap.min.js"></script>
            <!-- SlimScroll -->
            <script src="~/Areas/Admin//Data/plugins/slimScroll/jquery.slimscroll.min.js"></script>
            <!-- FastClick -->
            <script src="~/Areas/Admin//Data/plugins/fastclick/fastclick.min.js"></script>
            <!-- AdminLTE App -->
            <script src="~/Areas/Admin//Data/dist/js/app.min.js"></script>
            <!-- AdminLTE for demo purposes -->
            <script src="~/Areas/Admin//Data/dist/js/demo.js"></script>
            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

            <!--script custom page-->
            <!-- DataTables -->
            <script src="~/Areas/Admin//Data/plugins/datatables/jquery.dataTables.min.js"></script>
            <script src="~/Areas/Admin//Data/plugins/datatables/dataTables.bootstrap.min.js"></script>
            <script src="~/Areas/Admin//Data/plugins/datatables/dataTables.alphabetSearch.js"></script>

            <!-- page script -->
            <!--end script custom page-->
    </body>
</html>