Areas/Admin/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_KFC_WEB.Models;

namespace Project_KFC_WEB.Areas.Admin.Controllers
{
    public class CartsController : Controller
    {
        private KFC_Data db = new KFC_Data();

        // GET: Admin/Carts
        public ActionResult Index(int page = 1, bool isReset = false)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (isReset) Session["isSearchingCart"] = false;

            List<cart> carts = new List<cart>();
            bool isSearching = Session["isSearchingCart"] != null ? (bool)Session["isSearchingCart"] : false;

            var selectedOptionPrice = Request.QueryString["selectedOptionPrice"];
            var valueSearch = Request.QueryString["valueSearch"];

            carts = db.carts.Include(c => c.account).Include(c => c.food).ToList();
            if (!isSearching)
            {
                if (!string.IsNullOrEmpty(selectedOptionPrice) || !string.IsNullOrEmpty(valueSearch))
                {
                    isSearching = true;
                    Session["isSearchingCart"] = isSearching;
                    carts = SearchCart(carts, selectedOptionPrice, valueSearch);
                }
            }

            if (isSearching)
            {
                carts = Session["listCart"] as List<cart>;
                if (carts.ToList().Count() == 0) Session["isSearchingCart"] = false;
                carts = SearchCart(carts, selectedOptionPrice, valueSearch);
            }

            int itemsPerPage = 5;
            int totalItems = carts.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / itemsPerPage);

            page = Math.Max(1, Math.Min(page, totalPages));

            var startIndex = (page - 1) * itemsPerPage;
            var endIndex = Math.Min(startIndex + itemsPerPage - 1, totalItems - 1);

            List<cart> cartPage;

            if (startIndex < 0 || startIndex >= totalItems)
            {
                cartPage = null;
            }
            else
            {
                cartPage = carts.GetRange(startIndex, endIndex - startIndex + 1);
            }

            ViewBag.currentPage = page;
            Session["currentPageCart"] = page;
            ViewBag.totalPages = totalPages;

            return View(cartPage);
        }
        public List<cart> SearchCart(List<cart> carts, string selectedOptiontotalPrice, string valueSearch)
        {
            if (!string.IsNullOrEmpty(selectedOptiontotalPrice))
            {
                var number = Convert.ToInt32(string.Join("", selectedOptiontotalPrice.Split('-')[0].Trim().Split('.')));

                if (number == 0)
                {
                    carts = carts.FindAll(item => item.totalPrice >= 0 && item.totalPrice < 10000);
                }
                else if (number == 10000)
                {
                    carts = carts.FindAll(item => item.totalPrice >= 10000 && item.totalPrice < 50000);
                }
                else if (number == 50000)
                {
                    carts = carts.FindAll(item => item.totalPrice >= 50000 && item.totalPrice < 100000);
                }
                else if (number == 100000)
                {
                    carts = carts.FindAll(item => item.totalPrice >= 100000 && item.totalPrice < 500000);

                }
                else if (number == 500000)
                {
                    carts = carts.FindAll(item => item.totalPrice >= 500000 && item.totalPrice < 1000000);

                }
                else if (number == 1000000)
                {
                    carts = carts.FindAll(item => item.totalPrice >= 1000000);

                }
            }

            if (!string.IsNullOrEmpty(valueSearch)) carts = carts.FindAll(item => item.account.name.ToLower().Contains(valueSearch.Trim().ToLower()));

            Session["listCart"] = carts;

            return carts;
        }

        // GET: Admin/Carts/Details/5
        public ActionResult Details(int? id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cart cart = db.carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // GET: Admin/Carts/Create
        public ActionResult Create()
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            ViewBag.userName = new SelectList(db.accounts, "userName", "name");
            ViewBag.idFood = new SelectList(db.foods, "id", "name");
            return View();
        }

        // POST: Admin/Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,idFood,userName,quantity,totalPrice")] cart cart)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (ModelState.IsValid)
            {
                db.carts.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.userName = new SelectList(db.accounts, "userName", "name", cart.userName);
            ViewBag.idFood = new SelectList(db.foods, "id", "name", cart.idFood);
            return View(cart);
        }

        // GET: Admin/Carts/Edit/5
        public ActionResult Edit(int? id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cart cart = db.carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            ViewBag.userName = new SelectList(db.accounts, "userName", "name", cart.userName);
            ViewBag.idFood = new SelectList(db.foods, "id", "name", cart.idFood);
            return View(cart);
        }

        // POST: Admin/Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,idFood,userName,quantity,totalPrice")] cart cart)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (ModelState.IsValid)
            {
                db.Entry(cart).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.userName = new SelectList(db.accounts, "userName", "name", cart.userName);
            ViewBag.idFood = new SelectList(db.foods, "id", "name", cart.idFood);
            return View(cart);
        }

        // GET: Admin/Carts/Delete/5
        public ActionResult Delete(int? id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cart cart = db.carts.Find(id);
            if (cart == null)
            {
                return HttpNotFound();
            }
            return View(cart);
        }

        // POST: Admin/Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            cart cart = db.carts.Find(id);
            db.carts.Remove(cart);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Controllers/DiscountCodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_KFC_WEB.Models;

namespace Project_KFC_WEB.Areas.Admin.Controllers
{
    public class DiscountCodesController : Controller
    {
        private KFC_Data db = new KFC_Data();

        // GET: Admin/DiscountCodes
        public ActionResult Index(int page = 1, bool isReset = false)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (isReset) Session["isSearchingDisCountCode"] = false;

            List<discountCode> discountCodes = new List<discountCode>();
            bool isSearching = Session["isSearchingFoodCategory"] != null ? (bool)Session["isSearchingDisCountCode"] : false;

            var valueSearch = Request.QueryString["valueSearch"];

            discountCodes = db.discountCodes.ToList();

            if (!isSearching)
            {
                if (!string.IsNullOrEmpty(valueSearch))
                {
                    isSearching = true;
                    discountCodes = discountCodes.FindAll(item => item.code.ToLower().Contains(valueSearch.Trim().ToLower()));
                    Session["listDiscountCode"] = discountCodes;
                }
            }

            if (isSearching)
            {
                discountCodes = Session["listDiscountCode"] as List<discountCode>;
                if (discountCodes.ToList().Count() == 0) Session["isSearchingDisCountCode"] = false;
                if (!string.IsNullOrEmpty(valueSearch))
                {
                    discountCodes = discountCodes.FindAll(item => item.code.ToLower().Contains(valueSearch.Trim().ToLower()));
                    Session["listDiscountCode"] = discountCodes;
                }
            }

            int itemsPerPage = 5;
            int totalItems = discountCodes.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / itemsPerPage);

            page = Math.Max(1, Math.Min(page, totalPages));

            var startIndex = (page - 1) * itemsPerPage;
            var endIndex = Math.Min(startIndex + itemsPerPage - 1, totalItems - 1);

            List<discountCode> discountCodePage;

            if (startIndex < 0 || startIndex >= totalItems)
            {
                discountCodePage = null;
            }
            else
            {
                discountCodePage = discountCodes.GetRange(startIndex, endIndex - startIndex + 1);
            }

            ViewBag.currentPage = page;
            Session["currentPageDiscountCode"] = page;
            ViewBag.totalPages = totalPages;


            return View(discountCodePage);
        }

        // GET: Admin/DiscountCodes/Details/5
        public ActionResult Details(int? id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            discountCode discountCode = db.discountCodes.Find(id);
            if (discountCode == null)
            {
                return HttpNotFound();
            }
            return View(discountCode);
        }

        // GET: Admin/DiscountCodes/Create
        public ActionResult Create()
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            return View();
        }

        // POST: Admin/DiscountCodes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,code,discount")] discountCode discountCode)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (ModelState.IsValid)
            {
                db.discountCodes.Add(discountCode);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(discountCode);
        }

        // GET: Admin/DiscountCodes/Edit/5
        public ActionResult Edit(int? id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            discountCode discountCode = db.discountCodes.Find(id);
            if (discountCode == null)
            {
                return HttpNotFound();
            }
            return View(discountCode);
        }

        // POST: Admin/DiscountCodes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,code,discount")] discountCode discountCode)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (ModelState.IsValid)
            {
                db.Entry(discountCode).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(discountCode);
        }

        // GET: Admin/DiscountCodes/Delete/5
        public ActionResult Delete(int? id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            discountCode discountCode = db.discountCodes.Find(id);
            if (discountCode == null)
            {
                return HttpNotFound();
            }
            return View(discountCode);
        }

        // POST: Admin/DiscountCodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bool isLogin = Session["login"] != null ? (bool)Session["login"] : false;

            if(!isLogin) return RedirectToAction("Login", "Home",new { isLogin = false });

            discountCode discountCode = db.discountCodes.Find(id);
            db.discountCodes.Remove(discountCode);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="content-language" content="vi" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <title>Admin KFC</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="icon" type="image/png" href="favicon.ico">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="~/Areas/Admin/Data/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Areas/Admin/Data/plugins/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Areas/Admin/Data/plugins/ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Areas/Admin/Data/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/Areas/Admin/Data/dist/css/skins/_all-skins.min.css">
    <link rel="shortcut icon" href="https://static.kfcvietnam.com.vn/images/web/kfc-logo.svg?v=5.0" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">

            <!-- Logo -->
            <a href="@Url.Action("Index", "Home")" class="logo" style="background-color: #333">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>KFC</b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg" style="color: red"> <img src="https://static.kfcvietnam.com.vn/images/web/kfc-logo.svg?v=5.0" class="img-circle" alt="User Image" style="height:30px; margin-right: 10px; margin-bottom: 5px "><b>Quản lí KFC</b></span>
            </a>

            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation" style="background-color: #333">
                <!-- Sidebar toggle button-->
                @*<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>*@
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <!--<li>
                            <a href="#">
                                <i class="fa fa-envelope-o"></i>
                                <span class="label label-success">4</span>
                            </a>
                        </li>-->
                        <!-- Notifications: style can be found in dropdown.less -->
                        <!--<li>
                            <a href="#">
                                <i class="fa fa-bell-o"></i>
                                <span class="label label-warning">10</span>
                            </a>
                        </li>-->
                        <!-- Tasks: style can be found in dropdown.less -->
                        <!--<li>
                            <a href="#">
                                <i class="fa fa-flag-o"></i>
                                <span class="label label-danger">9</span>
                            </a>
                        </li>-->
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/Data/images/avatar_admin.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs">Đinh Nhật Huy </span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header" style="background-color: #333">
                                    <img src="~/Data/images/avatar_admin.jpg" class="img-circle" alt="User Image">
                                    <p>
                                        Đinh Nhật Huy
                                        <small>Nhân viên xuất sắc sủa chuỗi nhà hàng KFC</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body" style="background-color: #333">
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Followers</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Sales</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Friends</a>
                                    </div>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="@Url.Action("CheckLogout", "Home")" class="btn btn-default btn-flat">Đăng xuất</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                    </ul>
                </div>

            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/Data/images/avatar_admin.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>Đinh Nhật Huy</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="header">Quản Lí Web KFC</li>
                    <li class="">
                        <a href="@Url.Action("Index", "Accounts")">
                            <i class="fa fa-dashboard"></i> <span>Quản lí tài khoản</span> @*<i class="fa fa-angle-left pull-right"></i>*@
                        </a>
                        @*<ul class="treeview-menu">
                <li><a href="Admin/Accounts/index"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                <li class="active"><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
            </ul>*@
                    </li>
                    <li class="">
                        <a href="@Url.Action("Index", "FoodCategories")">
                            <i class="fa fa-dashboard"></i> <span>Quản lí loại món ăn</span> @*<i class="fa fa-angle-left pull-right"></i>*@
                        </a>
                        @*<ul class="treeview-menu">
                <li><a href="Admin/Accounts/index"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                <li class="active"><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
            </ul>*@
                    </li>
                    <li class="">
                        <a href="@Url.Action("Index", "Foods")">
                            <i class="fa fa-dashboard"></i> <span>Quản lí món ăn</span> @*<i class="fa fa-angle-left pull-right"></i>*@
                        </a>
                        @*<ul class="treeview-menu">
                <li><a href="Admin/Accounts/index"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                <li class="active"><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
            </ul>*@
                    </li>
                    <li class="">
                        <a href="@Url.Action("Index", "Carts")">
                            <i class="fa fa-dashboard"></i> <span>Quản lí đơn hàng</span> @*<i class="fa fa-angle-left pull-right"></i>*@
                        </a>
                        @*<ul class="treeview-menu">
                <li><a href="Admin/Accounts/index"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                <li class="active"><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
            </ul>*@
                    </li>
                    <li class="">
                        <a href="@Url.Action("Index", "DiscountCodes")">
                            <i class="fa fa-dashboard"></i> <span>Quản lí mã giảm giá</span> @*<i class="fa fa-angle-left pull-right"></i>*@
                        </a>
                        @*<ul class="treeview-menu">
                <li><a href="Admin/Accounts/index"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
                <li class="active"><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
            </ul>*@
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper bg-gray-active">
            @RenderBody()
            <div style="height:100px;"></div>
        </div><!-- /.content-wrapper -->

    </div><!-- ./wrapper -->
    <!-- jQuery 2.1.4 -->
    <script src="~/Areas/Admin/Data/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="~/Areas/Admin/Data/bootstrap/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/Areas/Admin/Data/plugins/fastclick/fastclick.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Areas/Admin/Data/dist/js/app.min.js"></script>
    <!-- SlimScroll 1.3.0 -->
    <script src="~/Areas/Admin/Data/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Areas/Admin/Data/dist/js/pages/dashboard2.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Areas/Admin/Data/dist/js/demo.js"></script>

</body>
</html>

</html>